version: '3.7'
services:
  gitea:
    image: gitea/gitea
    container_name: gitea_web
    volumes:
      - data:/data
    ports:
      - "53000:3000"
      - "55522:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - VIRTUAL_HOST
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD
      - DOMAIN
      - SSH_DOMAIN
      - ROOT_URL
    logging:
      options:
        max-file: '3'
        max-size: 10m
    depends_on:
      - db
    restart: always
    networks:
      - proxy-network
      - gitea-network
  db:
    image: postgres:alpine
    container_name: gitea_db
    restart: always
    environment:
      - POSTGRES_DB=gitea
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD
      - TZ
    logging:
      options:
        max-file: '3'
        max-size: 10m
    networks:
      - gitea-network
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  data:
  db:

networks:
  proxy-network:
    external:
      name: proxy_network
  gitea-network:
    name: gitea_network

